// categories -> techniques by different tactics
// since same techniques under different tactics with different techID
// To-do: complete the dictionary for all categories with techniques
export const techniqueByCategoriesMobile = {
    InitialAccess: [
      "Techniques",
      "Drive-By Compromise",
      "Drive-By Compromise",
      "Lockscreen Bypass",
      "Replication Through Removable Media",
      "Supply Chain Compromise",
      "Compromise Software Dependencies and Development Tools",
      "Compromise Hardware Supply Chain",
      "Compromise Software Supply Chain",
    ],
  
    Execution: [
      "Techniques",
      "Command and Scripting Interpreter",
      "Unix Shell",
      "Native API",
      "Scheduled Task/Job",
    ],
  
    Persistence: [
      "Techniques",
      "Boot or Logon Initialization Scripts",
      "Compromise Application Executable",
      "Compromise Client Software Binary",
      "Event Triggered Execution",
      "Broadcast Receivers",
      "Foreground Persistence",
      "Hijack Execution Flow",
      "System Runtime API Hijacking",
      "Scheduled Task/Job",
    ],
  
    PrivilegeEscalation: [
      "Techniques",
      "Abuse Elevation Control Mechanism",
      "Device Administrator Permissions",
      "Exploitation for Privilege Escalation",
      "Process Injection",
      "Ptrace System Calls",
    ],
  
    DefenseEvasion: [
      "Techniques",
      "Download New Code at Runtime",
      "Execution Guardrails",
      "Geofencing",
      "Foreground Persistence",
      "Hide Artifacts",
      "Suppress Application Icon",
      "User Evasion",
      "Hooking",
      "Impair Defenses",
      "Prevent Application Removal",
      "Device Lockout",
      "Disable or Modify Tools",
      "Indicator Removal on Host",
      "Uninstall Malicious Application",
      "File Deletion",
      "Disguise Root/Jailbreak Indicators",
      "Input Injection",
      "Native API",
      "Obfuscated Files or Information",
      "Steganography",
      "  Software Packing",
      "    Process Injection",
      "Ptrace System Calls",
      "Proxy Through Victim",
      "Subvert Trust Controls",
      "Code Signing Policy Modification",
      "Virtualization/Sandbox Evasion",
      "System Checks",
    ],
  
    CredentialAccess: [
      "Techniques",
      "Access Notifications",
      "Clipboard Data",
      "Credentials from Password Store",
      "Keychain",
      "Input Capture",
      "Keylogging",
      "GUI Input Capture",
      "Steal Application Access Token",
      "URI Hijacking",
    ],
  
    Discovery: [
      "Techniques",
      "File and Directory Discovery",
      "Location Tracking",
      "Remote Device Management Services",
      "Impersonate SS7 Nodes",
      "Network Service Scanning",
      "Process Discovery",
      " Software Discovery",
      "Security Software Discovery",
      "System Information Discovery",
      "System Network Configuration Discovery",
      "System Network Connections Discovery",
    ],
  
    LateralMovement: [
      "Techniques",
      "Exploitation of Remote Services",
      "Replication Through Removable Media",
    ],
  
    Collection: [
      "Techniques",
      "Access Notifications",
      "Adversary-in-the-Middle",
      "Archive Collected Data",
      "Audio Capture",
      "Call Control",
      "Clipboard Data",
      "Data from Local System",
      "  Input Capture",
      "Keylogging",
      "GUI Input Capture",
      "    Location Tracking",
      "Remote Device Management Services",
      "Impersonate SS7 Nodes",
      "Protected User Data",
      "Calendar Entries",
      "Call Log",
      "Contact List",
      "SMS Messages",
      "Screen Capture",
      "Stored Application Data",
      "Video Capture",
    ],
  
    CommandAndControl: [
      "Techniques",
      "Application Layer Protocol",
      "Web Protocols",
      "Call Control",
      "Dynamic Resolution",
      "Domain Generation Algorithms",
      "Encrypted Channel",
      "Symmetric Cryptography",
      "Asymmetric Cryptography",
      "Ingress Tool Transfer",
      "Non-Standard Port",
      "Out of Band Data",
      "Web Service",
      "Dead Drop Resolver",
      "Bidirectional Communication",
      "One-Way Communication",
    ],
  
    Exfiltration: [
      "Techniques",
      "Exfiltration Over Alternative Protocol",
      "Exfiltration Over Unencrypted Non-C2 Protocol",
      "Exfiltration Over C2 Channel",
    ],
  
    Impact: [
      "Techniques",
      "Account Access Removal",
      "Call Control",
      "Data Encrypted for Impact",
      "Data Manipulation",
      "Transmitted Data Manipulation",
      "Endpoint Denial of Service",
      "Generate Traffic from Victim",
      "Input Injection",
      "Network Denial of Service",
      "SMS Control",
    ],
  };